[package]
edition = "2021"
name = "sheeter"
version = "0.1.0"

[dependencies]
clap = { version = "3.1.0", features = ["derive"] }
rustfft = "6.0.1"
wav = "1.0.0"
midly = "0.5.2"
pix = "0.13.1"
image = "0.24.0"